name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 2 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: |
            Issue marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs.
          stale-pr-message: |
            Pull request marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs.
